version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build -- --mode ${ENVIRONMENT}
artifacts:
  files:
    - '**/*'
  base-directory: dist
